name: Minecraft Bedrock Server

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # chạy lại mỗi 6 tiếng để giữ server sống

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Start Minecraft Bedrock Server
      run: |
        sudo apt update
        sudo apt install screen wget unzip -y
        mkdir bedrock-server
        cd bedrock-server
        wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.62.01.zip
        unzip bedrock-server-1.20.62.01.zip
        chmod +x bedrock_server
        screen -dmS mc ./bedrock_server
        echo "Server started!"
        sleep 21600  # giữ server sống trong 6 tiếng (21600 giây)
